### ISSUE TITLE
Missing Samplers!

### ISSUE THREAD

**Issue by xidus90** [AIrjen/OneButtonPrompt#106]
There are some Sampling methods missing!
What about load them dynamicly?

1111:
![image](https://github.com/AIrjen/OneButtonPrompt/assets/10977056/c8c93968-6429-43af-ad4d-ef0eedad3c63)

OneButtonPromt:
![image](https://github.com/AIrjen/OneButtonPrompt/assets/10977056/014801f6-1ad4-469a-aa3f-1b978b562cc8)

**Comment by AIrjen** [comment]
Interesting. The list A1111 is also actually hardcoded. Turns out it does something more somewhere? I'll try and see if I can move it over to something more dynamic when I have time.

**Comment by AIrjen** [comment]
Made it dynamic, let me know if it works for you. No idea how you get the Exponential Sampler? Is it from the latest dev build?
