### ISSUE TITLE
Image height and width issues

### ISSUE THREAD

**Issue by Kking1111** [AIrjen/OneButtonPrompt#108]
Request to add custom image size rather than limited 3 options. Please add height and width just like the webui. This extension is great but can be made better. Also I saw a message "It is illegal to generate this prompt" in the background cmd.exe. Please dont limit this prompt generator to not generate prompts, it will limit the creativity.
![C](https://github.com/AIrjen/OneButtonPrompt/assets/130308556/fad89eef-0d12-44c6-b563-b9e70eab46b8)

**Comment by AIrjen** [comment]
Hi! This is just the base size, you can select the ratio’s as well. Or go even wild with wild mode. If you do want to select a very specific image width or height, you can always use the normal generate process.

as for your other question, it does not limit any prompts. There is a large set of joke messages that can randomly pop up. That was one of them 😅
