### ISSUE TITLE
Suffix removing commas

### ISSUE THREAD

**Issue by goblin776655** [AIrjen/OneButtonPrompt#109]
I enter to suffix <lyco:Margot RobbieV2:1> ,  <lora:add_detail:1.3>
And in log have just <lyco:Margot RobbieV2:1>  <lora:add_detail:1.3> without comma!

**Comment by AIrjen** [comment]
Hi! Yes, this is very confusing. One Button Prompt moves all Lora/Lyco's etc to the end of the prompt. Even if they we're already in the suffix. During this, it loses the comma.
A1111 actually doesn't process these as part of the prompt: https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Features#lora
It removes them when processing.

So, everything is working as intended. It's just that it is confusing.
