### ISSUE TITLE
"Filter out" not working?

### ISSUE THREAD

**Issue by Jonseed** [AIrjen/OneButtonPrompt#124]
I really like this extension. Well done! I'm interested in filtering out some words from the prompts, but the filter out field doesn't seem to be working. I put comma-separated words in that field like "film grain" and "render" (without the quotes) and yet I still get images with those terms in the prompt. Am I doing something wrong?

**Comment by AIrjen** [comment]
Hi, I am unable to test things right now. Can you take a look at this? user_guides/custom_files.md
here it describes how to create a standard antilist csv file.
I am also reading through the code, it might also have to do with spaces. So you can also try:
film grain,3d render,cat,purple

So no spaces between the words. It also needs a complete match, so “render” alone might not work.

**Comment by Jonseed** [comment]
Ok, thanks, I'll try the antilist csv file.

**Comment by Jonseed** [comment]
@AIrjen the antilist csv file doesn't seem to work either. It is still including terms in my prompts that are in the antilist csv file.

**Comment by AIrjen** [comment]
Hi, thanks for trying things out. I’ll try and see when I can pick this up to test and see where the code doesn’t work properly. I currently don’t have access to a computer so it might take a few weeks before I can properly fix it!

**Comment by AIrjen** [comment]
Hello! Sorry for the delay. I have taken a look, and it did work before, but there were issues with capital letters and other minor differences. So I added a small stability fix for this. It now works more stable than before.
Hope it does for you as well.

If not, please add the csv file you are using here. I can then take a more indepth look.
