### ISSUE TITLE
Please do not force the formatting

### ISSUE THREAD

**Issue by zffffff** [AIrjen/OneButtonPrompt#128]
![image](https://github.com/AIrjen/OneButtonPrompt/assets/21136110/b3132568-04be-45ca-859a-435b4edae519)

I need this format in my prompt words:
`AAA,BBB[xxx<LoRA_A>:yyy<LoRA_B>:0.3],zzz<LoRA:C>//////,`
But it will be forced to adjust to:
`AAA,BBB[xxx:yyy:0.3],zzz//////, ***<LoRA_A> <LoRA_B> <LoRA:C>`

There is another situation, for example:
`[<AAA,<LoRA:A>>:<BBB,CCC>:0.5],`
will become:
`[>::0.5], ***, <AAA,<LoRA:A> <BBB,CCC>`

or:
`[AAA,<LoRA:A>:BBB,CCC:0.5],`
will become:
`[AAA:BBB,CCC:0.5], ***, <LoRA:A>`

**Comment by AIrjen** [comment]
Hi!

What you are trying to do is not supported by A1111. Please refer to the documentation:

https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Features#lora

Basically, prompt switching is not supported for Loras and hypernetworks. The names etc are actually removed from the prompt before processing. One button prompt just pushes them to the end first for better readability.
The position of the lora does not matter at all.

Hope this clears things up!

**Comment by AIrjen** [comment]
I am a bit confused why its written like <lora:filename:multiplier:1:LWB=INALL>

Where does the :1:LWB=INALL come from?

**Comment by AIrjen** [comment]
Basically, this is the correct way of writing the prompt:

AAA,BBB,[xxx:yyy:0.3],zzz//////, ***<LoRA_A> <LoRA_B> <LoRA:C>

**Comment by zffffff** [comment]
> 

Thanks for telling me this tip, I really didn't know this rule. But in fact, I mainly do it for the convenience of reading. My logical thinking ability is not very strong. So can you please add a transfer switch? to control whether forced format conversion is required. Because sometimes I use <> to mark some content to facilitate my own understanding. I really haven't found a comprehensive official document that specifically explains the usage specifications of symbols.

**Comment by zffffff** [comment]
> I am a bit confused why its written like lora:filename:multiplier:1:LWB=INALL
> 
> Where does the :1:LWB=INALL come from?

An extension to help control Lora more precisely

https://github.com/hako-mikan/sd-webui-lora-block-weight

**Comment by AIrjen** [comment]
Hi, yeah it’s a good suggestion to make it into an option! I currently don’t have a development enviroment, so it might take a while 😅

**Comment by zffffff** [comment]
> Hi!
> 
> What you are trying to do is not supported by A1111. Please refer to the documentation:
> 
> https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Features#lora
> 
> Basically, prompt switching is not supported for Loras and hypernetworks. The names etc are actually removed from the prompt before processing. One button prompt just pushes them to the end first for better readability. The position of the lora does not matter at all.
> 
> Hope this clears things up!

https://github.com/cheald/sd-webui-loractl

I encountered a new situation. LoRA may now reflect different weights in different positions. This usage may be more in line with the usage habits of users like me, so I request you to add a switch that does not force the format.

I haven't found this switch in the build so far, so I'm guessing it's not there yet

**Comment by AIrjen** [comment]
Hi! I have done a quick change for you. The movement of the LoRA's is now turned off. I will bring it back as an option when I have some more time. :)

**Comment by zffffff** [comment]
Thank you,great work!
