### ISSUE TITLE
body_types_addon.csv needs to use commas instead of semicolons as in body_types.csv.

### ISSUE THREAD

**Issue by SchniuelZ** [AIrjen/OneButtonPrompt#143]
When adding body_types_addon.csv in userfiles\ you can't use  body_types.csv in csvfiles\ as template since body_types_addon.csv is expected to be in a comma separated list while body_types.csv is semicolon based. Really simple error to fix (either stick to commas or semicolons).

**Comment by AIrjen** [comment]
Hi! Woops, yeah that was a small bug. Got it fixed!

Will work on a better more coherent way of using comma's and semicolons, since it is now all over the place. Thanks for reporting this!
