### ISSUE TITLE
GradioUnusedKwargWarning

### ISSUE THREAD

**Issue by D0n-A** [AIrjen/OneButtonPrompt#145]
Hello. I think you are aware of this little thing, but when installing the extension on the latest version of AUTOMATIC1111, the following warnings appear:
```
...
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.6.0-2-g4afaaf8a
...
D:\AI\NS\modules\gradio_extensons.py:50: GradioUnusedKwargWarning: You have unused kwarg parameters in Row, please remove them: {'scale': 1}
res = original_BlockContext_init(self, *args, **kwargs)
create ui: done in 0.755s
...
```

I even tried installing on a clean version of the repository. Of the third-party extensions, specifically left only this one. I hope you fix it. Thank you.

**Comment by AIrjen** [comment]
Hi! Thanks for reaching out. I don't have this message on my install. But the message is clear enough, I think I know what to change!

**Comment by AIrjen** [comment]
Should be solved in latest version!
