### ISSUE TITLE
Add "Send to Negative Prompt" capabilities

### ISSUE THREAD

**Issue by Alyndiar** [AIrjen/OneButtonPrompt#151]
Could you add a negative prompt input and the ability to modify the negative prompt based on the random elements added to the positive prompt, especially in the case of Dynamic Prompts syntax. 

I like the method proposed here : [Sent to Negative](https://github.com/acorderob/sd-webui-sendtonegative)

So anything within <! !> is removed from the positive prompt and added to the negative prompt. This allows you to add things like:
- **Assassin <!Assassins Creed!>**     _# Create assassin but remove assassins creed influence_
- **{scifi|<!scifi!>|}**    _# Select between adding scifi style, removing scifi style and simply changing noting. Dynamic prompt syntax._

I'd do it myself if my coding experience was good enough 😭

**Comment by Alyndiar** [comment]
Also good for putting camera on the negative prompt when describing photo equipement so SD does not actually draw the camera...

**Comment by AIrjen** [comment]
Hi! I tried the extension you mentions, and it works well with One Button Prompt. If you want to use it, you can just add the <! !> syntax in the files.

here is how to do it, without breaking things on the next release:
https://github.com/AIrjen/OneButtonPrompt/blob/main/user_guides/custom_files.md#adding-on-to-or-replacing-one-button-prompt-main-lists

So you can install the mentioned extension, and then created replaced lists with the new syntax in.

I might consider looking at generating a negative prompt at some point, it is mostly the biggest unexplored space right now. But so far, have felt no direct need to do so.

**Comment by Alyndiar** [comment]
Is there a way to use it in ComfyUI? That's about the last thing preventing
me to switch to Comfy once and for all. That's why I was wondering about
adding negative prompt to your extension. Also, I'm not talking about you
generating a negative prompt. Just accepting a negative prompt to your
module and moving the negative parts to the negative prompt. I can do all
that no problem in A1111. I'm just looking for a way to do it in Comfy UI.

**Comment by AIrjen** [comment]
Hi, have you tried contacting the original creator, to see if he wants to create a ComfyUI node out of this?

**Comment by Alyndiar** [comment]
![image](https://github.com/AIrjen/OneButtonPrompt/assets/43357182/b296748e-6080-499f-a1a4-33eb4782b04c)

He's not interrested, but he also doesnt mind someone else doing it

**Comment by AIrjen** [comment]
Hello! I just pushed new logic for negative prompts in One Button Prompt:

https://github.com/AIrjen/OneButtonPrompt/blob/main/user_guides/auto_negative_prompt.md

It comes with a new "Auto Negative Prompt" node in ComfyUI as well.

It is not directly what you asked for, but you can configure it to work on the words you want. You can create a _addon file in the \userfiles\ folder. There is a sample included.
