### ISSUE TITLE
Negative prompt field has gone missing

### ISSUE THREAD

**Issue by Flerndip** [AIrjen/OneButtonPrompt#156]
Filter field remains but this is not the same as a negative input prompt.  It is still referenced in the help section but has gone conspicuously absent.  If it's going to ignore the main input prompts, the script's negative prompt field was not a superfluous feature.

**Comment by AIrjen** [comment]
Hi! Its not gone! It has been upgraded :D

It has got it's own tab:
![image](https://github.com/AIrjen/OneButtonPrompt/assets/130234949/e810c29a-5aca-4b74-a30f-cb5f89b74a58)

See the documentation here surrounding the new features:

https://github.com/AIrjen/OneButtonPrompt/blob/main/user_guides/auto_negative_prompt.md
