### ISSUE TITLE
Error during creation of images

### ISSUE THREAD

**Issue by Grimsanta** [AIrjen/OneButtonPrompt#162]
I keep getting an error similar to this screenshot
![Start A1111 2_10_2024 7_23_30 PM](https://github.com/AIrjen/OneButtonPrompt/assets/81027827/0cf51a0a-01ec-49b1-a09f-b771ab4acf80)

This happens randomly as sometimes I can do 5+ images (or batches of images if using quality gate). It can happen on the first images started or halfway through a set of images.

I was unsure of where to look to try to solve this or what exactly could be causing this and wanted to report it.

**Comment by AIrjen** [comment]
Thanks for reporting this! I will go have a look! I think the generated filename might be too long, but I need some time to investigate.

**Comment by AIrjen** [comment]
I got it solved! It was due to the filenames generated being too large. It now cuts off nicely.

If you download the latest version, it should work for you.
