### ISSUE TITLE
Unable to use the Save button

### ISSUE THREAD

**Issue by xfgexo** [AIrjen/OneButtonPrompt#17]
I noticed when using this it has an issue when it comes to saving an image/prompt. It gives me the following error in the console when attempting to save an image.

As a result the image and the prompt are not being saved when using the "Save" button while using this script.

Note: I have my Automatic 1111 configured to:

    Add number to filename when saving
    Do not save grids consisting of one picture
    Save text information about generation parameters as chunks to png files
    Create a text file next to every image with generation parameters.
     When using "Save" button, save images to a sub-directory

    I have the images being saved to a sub-directory on a different drive

My SD/Automatic 1111 is:

commit 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8 (HEAD -> master)
Merge: 65995a2e f71a3c9c
Author: AUTOMATIC1111 <[16777216c@gmail.com](mailto:16777216c@gmail.com)>
Date: Mon Feb 20 14:45:54 2023 +0300

___________________________________________________________

Error:Traceback (most recent call last):

File "D:\StableDifusion\stable-diffusion-webui\modules\call_queue.py", line 56, in f

res = list(func(*args, **kwargs))

File "D:\StableDifusion\stable-diffusion-webui\modules\ui_common.py", line 73, in save_files

fullfn, txt_fullfn = modules.images.save_image(image, path, "", seed=p.all_seeds[i], prompt=p.all_prompts[i], extension=extension, info=p.infotexts[image_index], grid=is_grid, p=p, save_to_dirs=save_to_dirs)

IndexError: list index out of range

Error completing request

___________________________________________________________

**Comment by AIrjen** [comment]
Thanks for reporting, this will be put on the todo list.

**Comment by AIrjen** [comment]
Morning! I was able to reproduce the problem by generating in batch, and trying to save from grid.

I was able to solve this issue, and pushed a fix for this. This should work now.
