### ISSUE TITLE
Adding wildcards is very difficult. Please make it simple.

### ISSUE THREAD

**Issue by DavideAlidosi** [AIrjen/OneButtonPrompt#171]
I had the unfortunate idea of adding new wildcards to existing ones.... Since the Dynamic Prompt extension is not compatible with AnimateDiff.
The task was very arduous, I had to do reverse engineering on the build_dynamic_prompt file, not exactly a piece of cake.
Interesting also the comment "# lol, this needs a rewrite :D", really appropriate.
Anyway, is there any plan to directly load all the .csv files in a directory, Dynamic Prompt style?
I think this is much better than editing lines and lines of code in a key file.

**Comment by AIrjen** [comment]
Hi, I am not sure what you are trying to do.

Here is a description of the options available:
https://github.com/AIrjen/OneButtonPrompt/blob/main/user_guides/custom_files.md

You can extend or overwrite existing .csv files, or add custom lists to add stuff in the start, middle or end of the prompt.

I haven't used animatediff, is there something that needs to be build into One Button Prompt for this? Maybe I can add something that helps support what you want to achieve.

**Comment by DavideAlidosi** [comment]
What I would like would be a way to simply add new files to those loaded by default.
Currently you need to add the names and references manually in the build_dynamic_prompt.py file to lines: 316, 3092, 3234, 3496, 3907, 4039.
If it were possible I would like to be able to load CSV files directly from the userfiles folder, seplly using the -filename- syntax.

**Comment by AIrjen** [comment]
Thanks, I understand! Give some time, shouldn't be to hard to add (I think?) :D

**Comment by DavideAlidosi** [comment]
That's superfast! I'll try it soon! Thanks a lot!

**Comment by DavideAlidosi** [comment]
I updated the repo, but I can't get the csvs to work, in the propt used instead of a list term appears -filename-.
Also would it be possible to add a subfolder, like \userfiles\mycsv to mat it neater?
thanks.

**Comment by AIrjen** [comment]
Ciao! I've done the following:
- Made a wildcards folder under user_files
- made an example file :)
- Made it possible to use .txt as well as .csv
- Made it possible to nest custom wildcards (but not built-in wildcards)

I have included a sample file as well. The filename itself doesn't need the - - , that why it wasn't working for you.

Hope this helps!
![image](https://github.com/AIrjen/OneButtonPrompt/assets/130234949/34cec4a6-e79a-4cff-8705-3abfcc1854d0)

**Comment by DavideAlidosi** [comment]
Thanks a lot for quick support, I'm able to meke it work on my side now!
Bests
