### ISSUE TITLE
Not outputting text to Showtext pysssss

### ISSUE THREAD

**Issue by S0LTIS** [AIrjen/OneButtonPrompt#173]
Not outputting text to Showtext pysssss

![image](https://github.com/AIrjen/OneButtonPrompt/assets/124645295/aa427285-7411-4b92-a693-bd7b3c071f72)

**Comment by AIrjen** [comment]
I can't get Show Text to work at all, it looks that Show Text has broken down somehow.

**Comment by AIrjen** [comment]
For me, I tried again this morning. Now it works again. No idea why, maybe something updated?

I have also left a comment here: https://github.com/pythongosssss/ComfyUI-Custom-Scripts/issues/218

![image](https://github.com/AIrjen/OneButtonPrompt/assets/130234949/4bf7c34c-9f18-412a-9335-35c1d4f02c40)
