### ISSUE TITLE
Prompt enhancer not work as expected if a wildcard is loaded into a preset

### ISSUE THREAD

**Issue by DavideAlidosi** [AIrjen/OneButtonPrompt#177]
If a Dynamic Prompt's wildcard is loaded into a preset and Prompt enhancer is active, One Button Prompt give to me some errors like this:
`Failed persuasion attempt... Retrying...`
In some way is funny!

**Comment by AIrjen** [comment]
Hi!

Thanks for trying out the superprompt integration :) I hope you like it!

I made a note of it here: https://github.com/AIrjen/OneButtonPrompt/blob/main/user_guides/superprompt.md#help-sometimes-it-takes-very-long-to-get-a-prompt-back-it-looks-stuck

Its something I've done to force SuperPrompt to get the values from subject/outfit overrides and checks the results if they are all there. If they are missing, it will retry, and spout a nonsense message :)

It's working, and it will automatically stop after 10 tries if it doesn't fully get there.

**Comment by DavideAlidosi** [comment]
Superprompt is great! Thanks to add it!

**Comment by DavideAlidosi** [comment]
Be that as it may, why does this seem to happen only with Dynamic Prompt wildcards and not with CSVs loaded directly into OneButton?

**Comment by DavideAlidosi** [comment]
I did some more testing on wildcard vs. Superpromt, it seems they are two systems that are not compatible, is that correct?

**Comment by AIrjen** [comment]
Hi, sorry, I sent a message this morning, but it got lost :D

I did a small fix to ignore Dynamic Prompts in superprompt to prevent the looping when using Dynamic Prompt wildcards. But yes, they are incompatible. 

Dynamic Prompts logic is executed way after One Button Prompt is finished. superprompt doesn't know how to handle wildcards at all.

**Comment by DavideAlidosi** [comment]
Thanks, for the reply, I've already switched to One Button Prompt ones on last updates!
Bests.
