### ISSUE TITLE
Error in build_dynamic_prompt.py

### ISSUE THREAD

**Issue by VirusShell** [AIrjen/OneButtonPrompt#185]
_Line 4012_ in **build_dynamic_prompt.py** has an error in one of the wildcard items.

Where _allwildcardslistnohybrid_ is declared, it shows:
`"agecalculator-"`

Should be:
`"-agecalculator-"`

**Comment by AIrjen** [comment]
Great spot! Will fix this soon! Thanks VirusShell 😊
