### ISSUE TITLE
Notting about ELLA?

### ISSUE THREAD

**Issue by DavideAlidosi** [AIrjen/OneButtonPrompt#188]
A few days ago I had written a post about ELLA, doesn't anyone care?
https://github.com/AIrjen/OneButtonPrompt/discussions/186#discussion-6512711

**Comment by AIrjen** [comment]
Hi, it looks like there are some ComfyUI nodes you can use for this: https://github.com/kijai/ComfyUI-ELLA-wrapper

I think you can just hook up one button prompt into the prompt field.

**Comment by DavideAlidosi** [comment]
As usual, thank you for your response.
It seems that at the moment the current ComfyUI implementation of ELLA is somewhat limited, for example you cannot use negative prompt or ControlNet. Also it seems that it is not possible to command input text with an external node, as there is support for no input.
However, my question was referring more to A1111, which I did not actually specify.

![ComfyUI ELLA](https://github.com/AIrjen/OneButtonPrompt/assets/19665235/dc12c73f-f44c-466f-b5da-ecccf9da35b2)

**Comment by AIrjen** [comment]
Hi David,

I'm sorry, I can't be of help here. You would have better luck asking automatic1111 and the contributers there. ELLA is basically its own processing pipeline, that would need to be build into A1111 for proper support. Maybe someone might build an extension for it. I currently don't have the time nor the interest in doing this.

BTW, I see that the above code is already out of date, https://github.com/TencentQQGYLab/ComfyUI-ELLA is now active, and does support negative prompts and controlnet.

I guess its just waiting for someone to pick up the A1111 implementation. If its popular, it will show up someday :)

**Comment by DavideAlidosi** [comment]
That's a super hint! I've also ask to add the possibility to drive the prompts by an external input: https://github.com/TencentQQGYLab/ComfyUI-ELLA/issues/23.
Bests.
