### ISSUE TITLE
Error with superprompt:     AttributeError: 'NoneType' object has no attribute 'keys'

### ISSUE THREAD

**Issue by tusharbhutt** [AIrjen/OneButtonPrompt#190]
Hi,

I get an error whenever trying out the SuperPrompt plugin, see truncated data error data below.  The error does not occur when the extension is off.  

Here's an image of the settings used:

![image](https://github.com/AIrjen/OneButtonPrompt/assets/26264462/7bd092ca-ad2f-4868-9c65-c6940f4fa9c1)

*** Error completing request

    Traceback (most recent call last):
      File "C:\Applications\StableDiffusion\Automatic1111\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "C:\Applications\StableDiffusion\Automatic1111\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "C:\Applications\StableDiffusion\Automatic1111\modules\txt2img.py", line 106, in txt2img
        processed = modules.scripts.scripts_txt2img.run(p, *p.script_args)
      File "C:\Applications\StableDiffusion\Automatic1111\modules\scripts.py", line 773, in run
        processed = script.run(p, *script_args)
      File "C:\Applications\StableDiffusion\Automatic1111\extensions\OneButtonPrompt\scripts\onebuttonprompt.py", line 1347, in run
        base_prompt = build_dynamic_prompt(insanitylevel,subject,artist, imagetype, False, antistring, prefixprompt, suffixprompt,promptcompounderlevel, seperator,givensubject,smartsubject,giventypeofimage,imagemodechance,chosengender, chosensubjectsubtypeobject, chosensubjectsubtypehumanoid, chosensubjectsubtypeconcept,True,False,-1,givenoutfit, False, base_model, OBP_preset, promptenhancer)
      File "C:\Applications\StableDiffusion\Automatic1111\extensions\OneButtonPrompt\build_dynamic_prompt.py", line 3319, in build_dynamic_prompt
        superpromptresult = one_button_superprompt(insanitylevel=insanitylevel, prompt=subjectprompt, seed=seed, override_subject=givensubject, override_outfit=overrideoutfit, chosensubject=subjectchooser, gender=gender, restofprompt = startprompt + endprompt)
      File "C:\Applications\StableDiffusion\Automatic1111\extensions\OneButtonPrompt\build_dynamic_prompt.py", line 4759, in one_button_superprompt
        load_models()
      File "C:\Applications\StableDiffusion\Automatic1111\extensions\OneButtonPrompt\superprompter\superprompter.py", line 25, in load_models
        model = T5ForConditionalGeneration.from_pretrained(modelDir, torch_dtype=torch.float16)
      File "C:\Applications\StableDiffusion\Automatic1111\venv\lib\site-packages\transformers\modeling_utils.py", line 2657, in from_pretrained
        loaded_state_dict_keys = list(state_dict.keys())
    AttributeError: 'NoneType' object has no attribute 'keys'

**Comment by Grogutech** [comment]
Same here

**Comment by AIrjen** [comment]
Hi! It might mean that you are missing some requirements.

Check out the documentation here: https://github.com/AIrjen/OneButtonPrompt/blob/main/user_guides/superprompt.md

Basically, go to the `OneButtonPrompt\superprompter\ ` directory and execute the following command:

`$ pip install -r requirements.txt`

It needs at least the following pieces installed:

transformers
einops
accelerate
sentencepiece

It will download the model on first use, it will download into: \OneButtonPrompt\superprompter\model_files

You can remove that _model_files_ directory to trigger a redownload of the actual model.

Hope that helps!

**Comment by tusharbhutt** [comment]
> Hi! It might mean that you are missing some requirements.
> 
> Check out the documentation here: https://github.com/AIrjen/OneButtonPrompt/blob/main/user_guides/superprompt.md

I'll give that a try, but just curious as to why that's not done automatically?

**Comment by AIrjen** [comment]
Hi! Thanks for the anwer.

I'll give that a try, but just curious as to why that's not done automatically?
> I have no idea how :D

As for your issue, I have no clue. It fails in `venv\lib\site-packages\transformers\modeling_utils.py` which is part of the transformers that is part of the requirements for the installation.
I had this problem at the start, when `sentencepiece` was not installed correctly.

Not sure how else to help here.

**Comment by AndreRatzenberger** [comment]
I probably have some insights, since I get the same error... OP missed that the error starts way earlier

`Please note that existing prompt and negative prompt fields are (no longer) used
Starting generating the prompt
only generated these artists:by Robert Vonnoh, Hendrick Avercamp
*** Error verifying pickled file from /workspace/stable-diffusion-webui/extensions/OneButtonPrompt/superprompter/./model_files/pytorch_model.bin
*** The file may be malicious, so the program is not going to read it.
*** You can skip this check with --disable-safe-unpickle commandline argument.
***
    Traceback (most recent call last):
      File "/workspace/stable-diffusion-webui/modules/safe.py", line 137, in load_with_extra
        check_pt(filename, extra_handler)
      File "/workspace/stable-diffusion-webui/modules/safe.py", line 84, in check_pt
        check_zip_filenames(filename, z.namelist())
      File "/workspace/stable-diffusion-webui/modules/safe.py", line 76, in check_zip_filenames
        raise Exception(f"bad file inside {filename}: {name}")
    Exception: bad file inside /workspace/stable-diffusion-webui/extensions/OneButtonPrompt/superprompter/./model_files/pytorch_model.bin: pytorch_model/byteorder
---`

so it's because the model is in non-safe format.
unfortunately I use a preconfigured and hosted instance of a1111, so any ideas how I can work around that?

**Comment by AIrjen** [comment]
Thanks, will look into making using of the safetensor file soon!

**Comment by AIrjen** [comment]
Running through some old issues, should be solved by this: https://github.com/AIrjen/OneButtonPrompt/issues/182#issuecomment-2154222581
