### ISSUE TITLE
How to integrate into fooocus 2.3.1

### ISSUE THREAD

**Issue by andyhebear** [AIrjen/OneButtonPrompt#191]
fooocus2.3.1 support amd/intel/cpu ,but RuinedFooocus only supprt  Nvidia graphics card.
how can use  oneButtonPrompt in fooocus2.3.1

**Comment by AIrjen** [comment]
Hi, One Button Prompt is not available in normal fooocus. You can maybe try ComfyUI or maybe this A1111 fork? (https://community.amd.com/t5/ai/how-to-automatic1111-stable-diffusion-webui-with-directml/ba-p/649027)

Or just buy go buy a Nvidia graphics card :D
