### ISSUE TITLE
[Feature Request] add Lora without change to custom preset

### ISSUE THREAD

**Issue by AlChico85** [AIrjen/OneButtonPrompt#204]
Hi, first at all, i love your OneButtonPrompt so far, great work !

I just miss an option to add a Lora without change the One Button Preset to "Custom".
It would be helpful if there is an option to use any Lora, like in my case a Lightning or HyperSD Lora without change the preset in the Main Tab to "Custom".

**Comment by AIrjen** [comment]
Nice! I already got this one in progress! I am adding preset and suffix fields on the presets. Should have time to finish/release in the weekend.

You can always add the Lora to a style in WebUI/RuinedFooocus as a fallback.

**Comment by AIrjen** [comment]
Hi, if you update it should have the new fields available :)
