### ISSUE TITLE
Import failed comfyUI

### ISSUE THREAD

**Issue by Balthazear** [AIrjen/OneButtonPrompt#205]
before updating 
OneButtonPrompt works like a charm

after an update 
IMPORT FAILED 

![image](https://github.com/AIrjen/OneButtonPrompt/assets/157926925/9fe9fa75-dfa8-4233-ab11-fe44cc5d2717)

I tried reinstalling with comfy manager also uninstalling an reinstalling with git clone 
same error, keeps failing 

here is the full error traceback
 
![image](https://github.com/AIrjen/OneButtonPrompt/assets/157926925/55d41bdf-8e7a-42ba-b2d7-47c03dfaac50)

**Comment by AIrjen** [comment]
Thats.... unusual.

Can you check if the OneButtonPrompt folder looks like this?

![image](https://github.com/AIrjen/OneButtonPrompt/assets/130234949/360217e4-7d13-46d3-a252-4a16e6518a8f)

At least to see if the build_dynamic_prompt.py file is there?

**Comment by Balthazear** [comment]
yes, i do have the build_dynamic_prompt

here is a screenshot of the folder:

![image](https://github.com/AIrjen/OneButtonPrompt/assets/157926925/abac8e46-9999-464c-b6e3-4bb91de2271f)
![image](https://github.com/AIrjen/OneButtonPrompt/assets/157926925/2d19cc69-bdf0-4eab-82b3-68f031a3e7b7)

**Comment by AIrjen** [comment]
Hi! I tried several things:
- Full upgrade of ComfyUI
- Complete remove and reinstall of One Button Prompt
- Upgrade of ComfyUI manager
- Reinstall of ComfyUI manager

But I can't reproduce the problem.

You can try to see if another extension is conflicting?

You can move the other extension out of the custom_nodes folder temporarely and see if that works.

I haven't changed this specific part of the logic, that could potentially have broken this.

**Comment by Balthazear** [comment]
Hey, i first tried to do what you did without moving all the custom nodes folders.

1.     Full upgrade of ComfyUI
         ComfyUI was on the latest version

2.     Upgrade of ComfyUI manager and all other custom nodes
3.     Complete remove and reinstall of One Button Prompt
         uninstalled with the manager, restart, install with the manager and another restart

4.     Reinstall of ComfyUI manager ----no need for this step

I got it working on step 3, which i find weird because i already did all those steps.
but yeah, thank you very much, i really liked your OneButtonPrompt Custom nodes. now i can keep using those.

**Comment by AIrjen** [comment]
Awesome! Thanks for reporting back, glad it's not a widespread issue :D
