### ISSUE TITLE
Is it possible to support sd.next?

### ISSUE THREAD

**Issue by alex13by** [AIrjen/OneButtonPrompt#209]
Is it possible to support sd.next?

**Comment by AIrjen** [comment]
It already works on sd.next:

![image](https://github.com/AIrjen/OneButtonPrompt/assets/130234949/0b02c42f-695d-44ff-be60-8fbe3d089717)


It's under scripts, not under extensions.

The only thing that doesn't work in SD.Next is One Button Run and Upscale, but everything else just works as normal!
