### ISSUE TITLE
OBP Not working in Forge

### ISSUE THREAD

**Issue by BWDrum** [AIrjen/OneButtonPrompt#215]
In Forge, when I press the Custom or Standard buttons, nothing happens, no new menus pop up. Presets are all working as are the other tab options, just unable to control prompt options using Custom or Standard options, the UI just doesn't update on screen. 

TIA

**Comment by AIrjen** [comment]
Already reported here: https://github.com/AIrjen/OneButtonPrompt/issues/214

Basically, forge upgraded to Gradio 4 which One Button Prompt currently does not support. Need to rewrite the Gradui code (the UI). It is on the todo list!

**Comment by BWDrum** [comment]
Thank you for the response, will follow the original report.
