### ISSUE TITLE
Feature request: Random insanitylevel (complexity) option

### ISSUE THREAD

**Issue by Jonseed** [AIrjen/OneButtonPrompt#219]
It might be cool to add an option that randomizes the number of insanitylevel (complexity) of the generated prompt so it changes for each generation.

**Comment by AIrjen** [comment]
Hi Jonseed. Setting the insanitylevel to 0 will make it go random between 1 and 10. The interface won't let you, but you can do some trickery with the preset files or the default values.

Hope that helps!

**Comment by Jonseed** [comment]
Good to know! I'll try setting it to 0 in the preset file.
