### ISSUE TITLE
ComfyUI: The "prompt_g" and "prompt_l" outputs no longer split up prompt

### ISSUE THREAD

**Issue by RogueLikely** [AIrjen/OneButtonPrompt#220]
Fairly self explanatory. Both output the full prompt text, same as the "prompt" output. Changing the "prompt enhancer" to superprompt-v1 sometimes causes differences between the outputs, but the majority of the text remains the same.

![Screenshot 2024-08-28 at 19-01-14 ComfyUI](https://github.com/user-attachments/assets/091a1aec-6e74-477f-86b9-8b6693d5df64)

**Comment by AIrjen** [comment]
Yup! That's a bug! Will look into this.

**Comment by AIrjen** [comment]
Know how to fix this, will bring this in next release. If the gradio 4 moves takes too long, I'll push a fix earlier.

**Comment by AIrjen** [comment]
Hotfix released, should be fixed if you get latest version! Thanks for reporting this.
