### ISSUE TITLE
base model add FLUX?

### ISSUE THREAD

**Issue by ivanberry** [AIrjen/OneButtonPrompt#223]
is it possible add FLUX model as base model?

**Comment by tazztone** [comment]
> is it possible add FLUX model as base model?

well the extension errors out in my forge. looks like gradio 4 breaks it maybe. it works for you?

```
Traceback (most recent call last):
  File "C:\_stability_matrix\Data\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "C:\_stability_matrix\Data\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\route_utils.py", line 285, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\_stability_matrix\Data\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "C:\_stability_matrix\Data\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\blocks.py", line 1508, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "C:\_stability_matrix\Data\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\_stability_matrix\Data\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\_stability_matrix\Data\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\_stability_matrix\Data\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\utils.py", line 818, in wrapper
    response = f(*args, **kwargs)
  File "C:\_stability_matrix\Data\Packages\stable-diffusion-webui-forge\extensions\OneButtonPrompt\scripts\onebuttonprompt.py", line 1122, in obppreset_changed
    + [maingroup.update(visible=True)]
AttributeError: 'Group' object has no attribute 'update'
```

**Comment by Jonseed** [comment]
See my comment here about using the extension in Forge for Flux. It is broken, but still works: https://github.com/AIrjen/OneButtonPrompt/issues/214#issuecomment-2307271012

**Comment by RalFingerLP** [comment]
Just replace [this file](https://github.com/AIrjen/OneButtonPrompt/blob/84a74e1e077f6663ccabfe562b55468ef7c6fd6f/scripts/onebuttonprompt.py) from the pull request and you are good to go!

**Comment by tazztone** [comment]
> Just replace [this file] and you are good to go!

thanks. downloaed it and replaced the file in:
stable-diffusion-webui-forge\extensions\OneButtonPrompt\scripts 
now works a charm

**Comment by RalFingerLP** [comment]
> > Just replace [this file] and you are good to go!
> 
> thanks. downloaed it and replaced the file in: stable-diffusion-webui-forge\extensions\OneButtonPrompt\scripts now works a charm
> 
> (now it just needs to be pimped for flux :P )
> 
> edit: saving a custom preset produces this error: should i open a new issue instead?
> 
> ```
> TypeError: 'module' object is not callable
> Traceback (most recent call last):
>   File "C:\_stability_matrix\Data\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\queueing.py", line 536, in process_events
>     response = await route_utils.call_process_api(
>   File "C:\_stability_matrix\Data\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\route_utils.py", line 285, in call_process_api
>     output = await app.get_blocks().process_api(
>   File "C:\_stability_matrix\Data\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\blocks.py", line 1923, in process_api
>     result = await self.call_function(
>   File "C:\_stability_matrix\Data\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\blocks.py", line 1508, in call_function
>     prediction = await anyio.to_thread.run_sync(  # type: ignore
>   File "C:\_stability_matrix\Data\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
>     return await get_asynclib().run_sync_in_worker_thread(
>   File "C:\_stability_matrix\Data\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
>     return await future
>   File "C:\_stability_matrix\Data\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
>     result = context.run(func, *args)
>   File "C:\_stability_matrix\Data\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\utils.py", line 818, in wrapper
>     response = f(*args, **kwargs)
>   File "C:\_stability_matrix\Data\Packages\stable-diffusion-webui-forge\extensions\OneButtonPrompt\scripts\onebuttonprompt.py", line 1108, in act_obp_preset_save
>     return gr(choices=choices, value=obp_preset_name)
> TypeError: 'module' object is not callable
> ```

yeha, I didn´t try that myself yet, should be a new bug report 😊

**Comment by tazztone** [comment]
> yeha, I didn´t try that myself yet, should be a new bug report 😊

i am just a bit hesitant because it may be from the manual file replace fix we did

**Comment by AIrjen** [comment]
Sorry, I've been away for a while. User zappityzap found a fix for forge, and I just merged the code.

I also recommend looking at this: https://github.com/runew0lf/RuinedFooocus now also has support for Flux and GGUF files, and has integrated One Button Prompt support.
