### ISSUE TITLE
Feature Request: Add support for Invoke

### ISSUE THREAD

**Issue by Jonseed** [AIrjen/OneButtonPrompt#225]
I don't know if you saw, but [Invoke just had a major release](https://www.invoke.com/post/introducing-invoke-5-our-biggest-update-yet), and they've really updated their UI, and now with support for Flux. It seems like this is really going to take off. I would love to use OneButtonPrompt in Invoke. I think you can add [custom features through nodes](https://invoke-ai.github.io/InvokeAI/contributing/), which is probably very similar to the custom nodes you made for ComfyUI. I don't think there is anything like OneButtonPrompt currently in Invoke.

**Comment by AIrjen** [comment]
Hi Jonseed, it does look a lot like ComfyUI. I think it does need it's own repository, but it does seem like creating the same nodes as ComfyUI seem possible.

I'll investigate!

**Comment by Jonseed** [comment]
Awesome @AIrjen! I look forward to trying it in Invoke!

Thank you so much for a great extension! It is one of my favorites, and I use it every day.

**Comment by AIrjen** [comment]
Here you go! I had to make a seperate repository out of it.

https://github.com/AIrjen/OneButtonPrompt_X_InvokeAI

You can go to the \invokeai\nodes\ and then `git clone https://github.com/AIrjen/OneButtonPrompt_X_InvokeAI`

Have fun!

**Comment by Jonseed** [comment]
You are amazing, @AIrjen! Well done! I think Invoke users are really going to like this. Thank you!

**Comment by Jonseed** [comment]
@AIrjen you might consider contributing your node to the [Invoke community nodes list](https://invoke-ai.github.io/InvokeAI/nodes/contributingNodes/).

**Comment by Jonseed** [comment]
@AIrjen you inspired me to add my own custom node for expanding prompts with Ollama: https://github.com/invoke-ai/InvokeAI/pull/7002. This could actually work well together with One Button Prompt nodes for converting tag-based prompts into natural language prompts for Flux.

**Comment by AIrjen** [comment]
Nice! Yeah those combinations work very well with LLM's! Good job.
