### ISSUE TITLE
superprompt-v1 and "overwrite subject"

### ISSUE THREAD

**Issue by tazztone** [AIrjen/OneButtonPrompt#226]
hi.
when overwriting subject like:
![image](https://github.com/user-attachments/assets/29b9198c-e9bb-41cd-9f10-ca6c821d5a06)
and with superprompt-v1 enabled:
![image](https://github.com/user-attachments/assets/e5901370-d3b7-478f-8939-673d61edb8a3)
it changes `t4zz` to `tzz` often: 
![image](https://github.com/user-attachments/assets/b6c696ae-61b4-48fe-8938-21b85163ec4c)

also i get a ton of "errors" while generating. not sure if it's normal. because it takes forever for 4 prompts:
![image](https://github.com/user-attachments/assets/a932da1b-1b56-4c93-afbc-c9a1eb95d48d)

hope this helps, and thanks!
looking forward to using this with flux 
cheers

**Comment by AIrjen** [comment]
Hi, the superprompt model uses english words. if you add a custom subject, it does try to check the output of the superprompt model if the text exists. If not, it will retry for 10 times. This is why you are seeing the retry messages.

Maybe in this case but the t4zz in the prompt prefix or suffix instead could help.
