### ISSUE TITLE
Error upon generating

### ISSUE THREAD

**Issue by WeirdScience06** [AIrjen/OneButtonPrompt#32]
I just updated the extension but when trying to do a blank generation, nothing changed or added then I get the following error.

> Starting generating the prompt
Error completing request
Arguments: ('task(1h5yd9ci0sfqivw)', '', '', [], 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 4, <controlnet.py.UiControlNetUnit object at 0x000001FE2222B760>, <controlnet.py.UiControlNetUnit object at 0x000001FE2211CEE0>, <controlnet.py.UiControlNetUnit object at 0x000001FE222290F0>, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, 7, 'all', 'all', 'all', '', '', '', '1', 'none', False, '', '', 'comma', '', True, '', None, False, None, False, None, False, 50) {}
Traceback (most recent call last):
  File "C:\AI\stable-diffusion-webui\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "C:\AI\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\AI\stable-diffusion-webui\modules\txt2img.py", line 53, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "C:\AI\stable-diffusion-webui\modules\scripts.py", line 408, in run
    processed = script.run(p, *script_args)
  File "C:\AI\stable-diffusion-webui\extensions\OneButtonPrompt\scripts\onebuttonprompt.py", line 696, in run
    preppedprompt += build_dynamic_prompt(insanitylevel,subject,artist, imagetype, False, antistring, prefixprompt, suffixprompt,promptcompounderlevel, seperator,givensubject,smartsubject,giventypeofimage)
TypeError: build_dynamic_prompt() takes from 0 to 12 positional arguments but 13 were given

**Comment by AIrjen** [comment]
Hi! After this update you need to restart webui, a reload is not enough. There is a puthon caching mechanism in webui, that needs te be reset.

That should solve your issue!

**Comment by WeirdScience06** [comment]
Yes you are correct, that did indeed resolve the issue
