### ISSUE TITLE
path error

### ISSUE THREAD

**Issue by pjpmccarthy52** [AIrjen/OneButtonPrompt#5]
Team,
This may have been an error on my part during the install on my M1 Mac.   When I attempted to run the script for the first time I received an error that the artists.csv could not be found:  .\\csvfiless\\artists.csv not found.

I made and edit to the csv_reader.py file and updated the full_path var:
diff csv_reader.py csv_reader.py_bak
7c7
<     full_path = os.path.join(script_dir, "./csvfiles/" )
---
>     full_path = os.path.join(script_dir, ".\\csvfiles\\" )
24c24
<         full_path = os.path.join(script_dir, "./csvfiles/" )
---
>         full_path = os.path.join(script_dir, ".\\csvfiles\\" )

The script is working now.  Planning on having lots of fun with it tomorrow.  
Thanks!!

**Comment by AIrjen** [comment]
Hi! Interesting, I have someone on reddit with the same problem, but I can't seem to reproduce locally.
I can't seem to see your fix, can you show how you fixed it? I can then put that change in.

**Comment by AIrjen** [comment]
Ohh thanks, working on this

**Comment by AIrjen** [comment]
I've put this into the codebase. Thank you so much!
