### ISSUE TITLE
OBP no longer showing in Scripts

### ISSUE THREAD

**Issue by an303042** [AIrjen/OneButtonPrompt#51]
So this is odd, and most probably my fault, but can you think of a reason why One Button Prompt won't show up any more in Scripts. Not on t2i or i2i. I've noticed that after I added a bunch of extensions, so I've started removing them but still no joy. I also tried just reinstalling OBP but nothing.
Auto1111 is updated to latest.
Any ideas for me to try? thanks

**Comment by AIrjen** [comment]
Hi!

This behavior tends to happen when there is an error with One Button Prompt during startup. Can you check if there is any related message showing up during the startup process of WebUI.

Another thing to consider, I did push a small update a few hours ago. Did you update One Button Prompt today? If so, it might be one of the new changes that is causing the issue.

Let me know!

**Comment by an303042** [comment]
Thanks for replying!
Looked at the console at startup and found this:

```
Error loading script: onebuttonprompt.py
Traceback (most recent call last):
  File "F:\SD\stable-diffusion-webui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "F:\SD\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\SD\stable-diffusion-webui\extensions\OneButtonPrompt\scripts\onebuttonprompt.py", line 40, in <module>
    img2imgupscalerlist = get_upscalers_for_img2img()
  File "F:\SD\stable-diffusion-webui\extensions\OneButtonPrompt\model_lists.py", line 28, in get_upscalers_for_img2img
    upscalerlistfromwWebUI.remove("None")
ValueError: list.remove(x): x not in list

```
and yes - I updated on every run (living on the edge!)

**Comment by tsound97** [comment]
> 
Same Error :(

**Comment by AIrjen** [comment]
Amazing! I know what to fix. Please hold on :)

**Comment by AIrjen** [comment]
Got a fix out!

Issue was that in the latest release I noted a "None" upscaler showing up, so I changed to code to remove it.
Turns out, this isn't on everyones system. So it couldn't remove the "None" value, and stopped loading.

I changed it, so it now checks if the value exists before removing it.

**Comment by an303042** [comment]
Aaaaaand we're back on!
Thanks a bunch!
