### ISSUE TITLE
Can you get this to be compatible with Vladmandic? Currently it will not even install

### ISSUE THREAD

**Issue by cleverestx** [AIrjen/OneButtonPrompt#59]
It gives a TYPE error and hoses the UI, forcing a deletion of the html\extensions.json file in Valdmandic's program folder to even bring up the UI again...bummer, I really want to use this...also, Valdmandic does not support a webui-user.bat file so it's not possible to use the --api switch.

**Comment by chuckkay** [comment]
I can confirm same problem with Vlad Diffusion

**Comment by AIrjen** [comment]
Thanks for reporting, last time I checked it didn’t break things, and it shouldn’t. I do need some free time to investigate this, hopefully I can make some this weekend.

**Comment by Seantourage** [comment]
I'm not having issues using --listen

It doesn't seem to see the aesthetic scorer but probably something on my end.

**Comment by chuckkay** [comment]
> I'm not having issues using --listen
> 
> It doesn't seem to see the aesthetic scorer but probably something on my end.

you are correct, it works (NEED TO REMOVE --API arg. not needed, blocks install)  
seems to be workinbg now with --listen

**Comment by Blackened15** [comment]
Am I missing something? using SDNext seems I can only get thumbnail to be saved. If I use the parameter saved into these PNG, I get the same picture, at the proper expected size.

`(art by Bob Eggleton:1.2) , photograph, modelshoot style shot of a Impeccable tall Hellenistic girl, 🤔, Producing a TV show, wearing Biophilic Magic Halter dress, Braided bun hair, Scottish Scarf, Soul Patch, studio lighting, film grain, Ilford HP5, 80mm, Highres
Negative prompt: bad-artist-anime bad-artist NG_DeepNegative_V1_75T Steps: 20, Sampler: DDIM, CFG scale: 6.0, Seed: 488726873, Size: 768x512, Model hash: dde3b17c05, Model: Latest_A-Zovya_Photoreal_V2, VAE: vae-ft-ema-560000-ema-pruned.vae, Seed resize from: -1x-1, Denoising strength: 0.6, Clip skip: 1, Version: b6ac47e, Parser: Full parser`

**Comment by AIrjen** [comment]
Hi, thanks everyone for the info and comments.

I created a fresh install of Vladmandic (latest version) and was able to install OneButtonPrompt without issues.
For Vladmandic, it seems that the --api option is indeed not needed at all. This is enabled by default, and thus One Button Run and Upscale will just work out of the box with Vlad.

For cleverestx, if you are not using any flags, and are working on latest version, the install should just work.
If you still have problems, you can try the following:
- Install OneButtonPrompt via Automatic WebUI, and just copy the extension folder over to vlad's extension folder
- Download the files manually, and put those in the vlad's extension folder:
![image](https://github.com/AIrjen/OneButtonPrompt/assets/130234949/2c0a8ee7-5b68-4d11-90f2-59e422fbfb62)

Let me know if any of the proposed solutions have worked for you.

I think it's time to make a F.A.Q. and store this information surrounding Vlad.

**Comment by cleverestx** [comment]
I did the zip method, opened it fine, shows it installed under extension, but not visible anywhere...clicked to apply and restart from extensions...and it won't open Vlad again, I get this error:

TypeError: can only concatenate str (not "list") to str

![image](https://github.com/AIrjen/OneButtonPrompt/assets/28905253/d32e60e7-765e-4aa0-9a6c-44ac64038066)

I may need to reinstall Vlad and try again I guess?

**Comment by cleverestx** [comment]
So if I delete this from the EXTENSIONS. JSON in vladmandic (in the HTML folder), I still cannot launch into Vladmandic again, so I have to delete the entire EXTENSIONS.JSON file to get back in:  (haven't reinstalled Vladmandic yet)

![image](https://github.com/AIrjen/OneButtonPrompt/assets/28905253/ba5db824-a7ab-4245-a172-e6c6dfee0090)

**Comment by AIrjen** [comment]
Hi, found the following (resolved) issue in vladmandic, which seems to reference this problem:
https://github.com/vladmandic/automatic/issues/1485

It looks like its already solved by Vlad (and caused by another extension). Are you sure you are running on the latest version of vladmandic? He is actively working on this part, you might just be on a version that is broken.
I tried various things:
- installing/uninstalling one button prompt
- refreshing extension list
- deleting EXTENSIONS.JSON and then refreshing extension lists
- various restarts

Everything seems stable on my end.

Also, if you can post the stack trace of the error, that would be very helpful. That should be the part above the "TypeError" message, if there is any.

**Comment by cleverestx** [comment]
Confirmed it works! Thank you!! I just had to GIT PULL my Vladmandic. I thought it was auto-updating on every launch as I would see occasional updates that way, but apparently not...
