### ISSUE TITLE
[Broke] takes from 0 to 13 positional arguments but 14 were given

### ISSUE THREAD

**Issue by medledan** [AIrjen/OneButtonPrompt#60]
**version: [v1.3.2]  •  python: 3.10.6  •  torch: 2.0.0+cu118  •  xformers: 0.0.17  •  gradio: 3.32.0  •  checkpoint: [e4a30e4607]**

Please note that existing prompt and negative prompt fields are (no longer) used
Starting generating the prompt
Error completing request
Arguments: ('task(e6wqiii7r9jzr34)', '', 'negative_hand-neg, easynegative:0.5, lowres, low quality:1.4, worst quality:1.4, bad eyes, monochrome, greyscale, signature, watermark, deformed pupils, deformed iris', [], 50, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, True, 0.35, 2, 'R-ESRGAN 4x+', 15, 0, 0, 0, '', '', [], 4, 0, 0, 2, 512, 512, True, 'R-ESRGAN 4x+', 'None', 0, True, 'keyword, prompt', 'Mature Adult', 'None', 'model keyword first', 'None', '1.2', 'None', False, 'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 1, 'None', 2, False, 10, 1, 1, 64, False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 1536, 96, True, True, True, False, True, False, 1, False, False, False, 1.1, 1.5, 100, 0.7, False, False, True, False, False, 0, 'Gustavosta/MagicPrompt-Stable-Diffusion', '', <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000002DC8F4EA5C0>, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, 5, 'humanoid', 'realism', 'digital art', '', '', '', '1', 'none', False, '', '', 'comma', '', True, '', '20', '', '', 0, None, None, False, 50) {}
Traceback (most recent call last):
  File "G:\Automatic1111\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "G:\Automatic1111\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "G:\Automatic1111\modules\txt2img.py", line 54, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "G:\Automatic1111\modules\scripts.py", line 441, in run
    processed = script.run(p, *script_args)
  File "G:\Automatic1111\extensions\OneButtonPrompt\scripts\onebuttonprompt.py", line 736, in run
    preppedprompt += build_dynamic_prompt(insanitylevel,subject,artist, imagetype, False, antistring, prefixprompt, suffixprompt,promptcompounderlevel, seperator,givensubject,smartsubject,giventypeofimage,imagemodechance)
TypeError: build_dynamic_prompt() takes from 0 to 13 positional arguments but 14 were given

**Comment by AIrjen** [comment]
Yeah, I suppose I should make a F.AQ. sometimes with this in it. Glad you were able to solve it yourself :)

Happy prompting!
