### ISSUE TITLE
Lora/lyco names with spaces are formatted and thus not working

### ISSUE THREAD

**Issue by kuriot** [AIrjen/OneButtonPrompt#64]
Hi.

You don't need any lora to check that this problem exist. Just copy this `<lora:some lora(With description):0.5>` to "Overwrite subject" or any other field which works with user's input. And see how it will be transformed during generation to `<lora:some lora (With description) :0.5>`.

**Comment by AIrjen** [comment]
Thank you! Fixed it :) LoRA's and others are no longer "parsed" during the cleaning which caused this issue. They are stored seperately and then moved to the back of the prompt.

**Comment by kuriot** [comment]
Cool. You're breathtaking!
