### ISSUE TITLE
A way to remove known characters

### ISSUE THREAD

**Issue by jcbordo** [AIrjen/OneButtonPrompt#66]
I would like the prompt to never generate known fictional or non-fictional characters.  Should I just blank out the CSVs?  or replace them with random names?  I don't see an option to avoid them in the settings.

Amazing script by the way.  Thank you so much for making it.

**Comment by jcbordo** [comment]
ok, don't mind me.  I didn't see the custom folder, now I get it.

**Comment by AIrjen** [comment]
Hi!

Currently, the only way to turn things off is via creating a empty replacement override list. The code is already build to accept turning off lists, there is just no interface for it yet. This is on my todo list!

**Comment by AIrjen** [comment]
Update: There is now a config file in the latest version, where you can now easily turn off certain parts of the generation process. This should be exactly what you are looking for.

https://github.com/AIrjen/OneButtonPrompt/blob/main/user_guides/config_file.md
