### ISSUE TITLE
hello some more!

### ISSUE THREAD

**Issue by VelvetAcidChrist** [AIrjen/OneButtonPrompt#70]
It looks like you forgot to remove 68: print("hello some more!") in model_lists.py :)

**Comment by AIrjen** [comment]
Hahaha! Debugging lines are fun! Thanks for the notification 😊 Will push a fix soon! Not at home right now.

**Comment by AIrjen** [comment]
![image](https://github.com/AIrjen/OneButtonPrompt/assets/130234949/65e2a36f-e37d-421d-8e1d-157ae993b4f2)

Debug line removed :D
