### ISSUE TITLE
Request: Add "Restore faces" as an option.

### ISSUE THREAD

**Issue by ecopirate** [AIrjen/OneButtonPrompt#71]
Many thanks for this wonderful extension. 
Sorry if I am missing it and it is already there but if not could you please add an easy tick box to add "Restore Faces"?

**Comment by AIrjen** [comment]
Hi! Yes, I will put this on the development list for "One Button run and upscale". WebUI API also supports this. Not a big change, but need some time to put this in and test this.

You can use it during normal generation, like any other setting.

**Comment by ecopirate** [comment]
Great! Many thanks.
