### ISSUE TITLE
Request: Add Random Lora/TI/Lycoris to the prompt

### ISSUE THREAD

**Issue by ecopirate** [AIrjen/OneButtonPrompt#72]
Could you please add an option to add a Random Lora/TI/Lycoris to the prompt?

Or is there any other A1111 extension capable of doing that trick?

Thanks!

**Comment by ecopirate** [comment]
Help currently states that there should be an "Other prompt field"  but this does not appear to exist? 

Other prompt fields
The existing prompt and negative prompt fields are ignored.

Add a prompt prefix, suffix and the negative prompt in the respective fields. They will be automatically added during processing.

These can be used to add textual inversion and LoRA’s. They can also be used to add your models trigger words.

**Comment by AIrjen** [comment]
Hi! This already exists. Please refer to the documentation here: https://github.com/AIrjen/OneButtonPrompt/blob/main/user_guides/custom_files.md

Basically, add a file called styles_ti_lora.csv in the /user_files/ folder.
It will then randomly (not always!) pick a value from this file and add it to your prompt.

This should be exactly what you are looking for.

**Comment by ecopirate** [comment]
Awesome! Many thanks,
