### ISSUE TITLE
Prompt compounder does not replace templates in common prompt when active with Regional Prompter

### ISSUE THREAD

**Issue by lanice** [AIrjen/OneButtonPrompt#79]
I'm following the guide on [creating awesome landscapes with prompt compounder and Regional Prompter](https://github.com/AIrjen/OneButtonPrompt/blob/main/user_guides/prompt_compounder_and_regional_prompter_to_create_insane_images.md#creating-awesome-landscapes-with-prompt-compounder-and-regional-prompter-extension).

When generating, the common prompt seems to just contain the template name without being replaced by the actual value, e.g., `(-artist-:1.2)`.

Here is a full prompt generated with the settings from the documentation:
```
, [ (-artist-:1.2) ,-artist-:13], landscape
BREAK landscape of a Mysterious Hideous [Channel|Sagrada Familia], at Midday, Anime screencap, Grim, Minecraftcore, professional,
BREAK, studio On pale black paper, landscape of a Studied South Korea from inside of a Arch dam, Foggy conditions, Embarrassing, Modern European Ink Painting, 80mm, adobe lightroom,
BREAK, 8k Painting, landscape of a Daring Hyper-Creative Movie theater from inside of a Beach house, dense water, Spring, Wizardcore, F/8, Saturated
```

And another one:
```
, [ (-artist-:0.8) :-artist-:-artist-:16], landscape
BREAK Color splash, landscape of a Elusive Coral Reef, at Dusk, Simple illustration, Horror, F/2.8, Autochrome,
BREAK, Drawing, Bastardcore, landscape of a Twisted Shaky Eiffel Tower and Dune, Boorish dungeon, Summer, Realistic, Tranquil, Mono Color,
BREAK, landscape of a Ancient Glad Glasgow, at Dawn, Cel shading, Low shutter, Oversaturated
```

Awesome extension by the way!

**Comment by lanice** [comment]
As a sidenote, when using the Workflow assist with the exact same settings, the templates seem to get replaced. However, I think the regions are not counted correctly. Here are two generated prompts via the workflow assist, using the exact same settings as before:
```
art by Jack Gaughan, (art by Butcher Billy:1.2) , Metalcore, landscape of a Strange [Chile:The Arctic Ocean:3], at Blue hour, Graphic novel, Aspiring, Lens Flare, anaglyph effect, 
 BREAK, landscape of a 1900'S Golf course, [water|flora], at Dusk, Proud, Amaro, (art by Chiharu Shiota:0.9) , 
 BREAK, best quality, landscape of a Sad Sonoma Valley, Summer, art by Gemma Correll, (art by Keith Haring:1.1)
```
```
Shameful, Insensitive Deformed [Monument Valley|Great Wall of China] and Split, deep pink and Navy Blue hue, Colorless, broad lighting, Single Color, bloom, Candle light, Desaturated, halation, Peaceful, 
 BREAK, Satisfying, waning light, Irritated Peaceful Archipelago from inside of The Atlantic Ocean, 
 BREAK, Lonely, Kinemacolor, Foolish Bristol, four colors, Cold Colors, Suffering
```
Could it be that the common prompt is actually omitted here?

**Comment by AIrjen** [comment]
Thank you! Yes, the above is definitely a bug!

I will take a look at these soon, I'm working at a large update atm.

**Comment by lanice** [comment]
I figured out why it happened. Just opened a PR as fix suggestion, feel free to merge, or not if you think it breaks something :)

**Comment by AIrjen** [comment]
I just saw! Lets just go for it! That was what was on my mind as well. I recently changed everything to use wildcards, so yeah, this is the solution.

**Comment by AIrjen** [comment]
As for the above, yeah I think the common prompt is indeed omitted.

I want to do some more stuff for workflow prompt (I want to use wildcards in it!), but that is coming later.

**Comment by lanice** [comment]
Makes sense! I tried to fallback to using the workflow at first to generate something with the regional plus compound prompting, but then realized that it missed the common prompt. But now that the original issue is fixed I can use the normal generation :)
