### ISSUE TITLE
Default negative prompt, sufix, prefix?

### ISSUE THREAD

**Issue by goblin776655** [AIrjen/OneButtonPrompt#92]
Default negative prompt, sufix, prefix?
Some way to setup it one time and use it?
Not every time I start SD and type it manual!
Thanks!

**Comment by AIrjen** [comment]
Hi! You can add any default value as you would normally with any other value in WebUI. This is done by editing the ui-config.json file. You can search for onebuttonprompt in that file to find the settings you need to change.

Storing and loading settings has been requested before. It's on the todolist somewhere!
