### ISSUE TITLE
prefix becomes suffix when using <>

### ISSUE THREAD

**Issue by NNNenov** [AIrjen/OneButtonPrompt#94]
hello, I am trying to add `<hypernet:LuisapSciFiHard_v1:1>` as a prefix in one button prompt, instead it is placed at the end of the prompt. If  I use regular text, it is prefixed as expected.
One Button Prompt version fca8b1cd
using webui 1111 version 1.3.2

**Comment by AIrjen** [comment]
Hi, this is intended behavior. The placement of LoRA's and Hypernetworks are not affected by where they placement in the prompt. They are internally also moved to the end of the prompt. (https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Features#lora)

One Button Prompt recognizes them, and moves them to the end of the prompt as well. Making the prompt easier to read.

**Comment by NNNenov** [comment]
Apologies, I didnt realise, thank you for the fast response. Great work on this extension!

**Comment by AIrjen** [comment]
Yeah! I get it is confusing. Especially when you are expecting it to show up in the prefix.
